### ISSUE TITLE
Hii Bro 

### ISSUE THREAD

**Issue by UdhayakumarThangavel** [saikrishnasangu/test001#1]
Sorry to disturb you. I've a doubt in virtusa project 

Initially there was no spring app and react app I created it using npm and vs code extension.

but the `Junit` and `puppeteer` files are missing in my project. How I can get or add it for my project.

Thanks in advance.

![Screenshot 2023-05-16 071747](https://github.com/saikrishnasangu/test001/assets/60465112/9adc76f4-c0ee-4ef9-94b3-bf6e9b50cfa6)

**Comment by saikrishnasangu** [comment]
Are you a virtusa intern?

**Comment by UdhayakumarThangavel** [comment]
Yess

**Comment by saikrishnasangu** [comment]
Mail your issue to @***@***.*** ***@***.***>

**Comment by UdhayakumarThangavel** [comment]
Ok thanks
